package com.sig.view;
import javax.swing.*;

public class InvoiceCreation extends javax.swing.JDialog {

    /**
     * Creates new form newJDialog
     */
    private SalesInvoiceGeneratorJFrame parent;
    public InvoiceCreation( SalesInvoiceGeneratorJFrame  parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invoiceNumberLabel = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        CreationDateLabel = new javax.swing.JLabel();
        dialogBoxTitleLabel = new javax.swing.JLabel();
        confirmInvoiceCreationButton = new javax.swing.JButton();
        confirmInvoiceCreationButton.addActionListener(this.parent.getHandler());
        confirmInvoiceCreationButton.setActionCommand("confirmInvoiceCreationButton");
        cancelInvoiceCreationButton = new javax.swing.JButton();
        cancelInvoiceCreationButton.addActionListener(this.parent.getHandler());
        cancelInvoiceCreationButton.setActionCommand("cancelInvoiceCreationButton");
        invoiceNumTextField = new javax.swing.JTextField();
        customerNameTextField = new javax.swing.JTextField();
        creationDateTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create New Invoice");
        setResizable(false);

        invoiceNumberLabel.setText("Invoice Number");

        customerNameLabel.setText("Customer Name");

        CreationDateLabel.setText("Creation Date");

        dialogBoxTitleLabel.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        dialogBoxTitleLabel.setText("Create  New Invoice");

        confirmInvoiceCreationButton.setText("Confirm");
        confirmInvoiceCreationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmInvoiceCreationButtonActionPerformed(evt);
            }
        });

        cancelInvoiceCreationButton.setText("Cancel");
        cancelInvoiceCreationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelInvoiceCreationButtonActionPerformed(evt);
            }
        });

        customerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTextFieldActionPerformed(evt);
            }
        });

        creationDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creationDateTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CreationDateLabel)
                            .addComponent(customerNameLabel)
                            .addComponent(invoiceNumberLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(invoiceNumTextField)
                            .addComponent(customerNameTextField)
                            .addComponent(creationDateTextField))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 234, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(confirmInvoiceCreationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelInvoiceCreationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(dialogBoxTitleLabel)
                                .addContainerGap(234, Short.MAX_VALUE))))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelInvoiceCreationButton, confirmInvoiceCreationButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dialogBoxTitleLabel)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceNumberLabel)
                    .addComponent(invoiceNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameLabel)
                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreationDateLabel)
                    .addComponent(creationDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmInvoiceCreationButton)
                    .addComponent(cancelInvoiceCreationButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cancelInvoiceCreationButton, confirmInvoiceCreationButton});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelInvoiceCreationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelInvoiceCreationButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cancelInvoiceCreationButtonActionPerformed

    private void confirmInvoiceCreationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmInvoiceCreationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmInvoiceCreationButtonActionPerformed

    private void creationDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creationDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creationDateTextFieldActionPerformed

    private void customerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("com.formdev.flatlaf.flatdarklaf");
        } catch (ClassNotFoundException e) {
            throw new RuntimeException(e);
        } catch (InstantiationException e) {
            throw new RuntimeException(e);
        } catch (IllegalAccessException e) {
            throw new RuntimeException(e);
        } catch (UnsupportedLookAndFeelException e) {
            throw new RuntimeException(e);
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InvoiceCreation dialog = new InvoiceCreation(new SalesInvoiceGeneratorJFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CreationDateLabel;
    private javax.swing.JButton cancelInvoiceCreationButton;
    private javax.swing.JButton confirmInvoiceCreationButton;



    private javax.swing.JTextField creationDateTextField;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JLabel dialogBoxTitleLabel;
    private javax.swing.JTextField invoiceNumTextField;
    private javax.swing.JLabel invoiceNumberLabel;
    // End of variables declaration//GEN-END:variables

    public JTextField getCreationDateTextField() {
        return creationDateTextField;
    }

    public JTextField getCustomerNameTextField() {
        return customerNameTextField;
    }

    public JTextField getInvoiceNumTextField() {
        return invoiceNumTextField;
    }
}
